steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/gke-llm/torchtune:latest', '.']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/gke-llm/torchtune:latest'
